POST http://localhost:3069/auth/register HTTP/1.1
Content-Type: application/json

{
    "username" : "opr4moo",
    "email" : "test12@gmail.com",
    "password" : "qwerty123!"
}

###

POST http://localhost:3069/auth/login HTTP/1.1
Content-Type: application/json

{
    "username" : "user10",
    "password" : "Qwer123!"
}

###

GET http://localhost:3069/auth/keeplogin HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzYsInVzZXJuYW1lIjoidXNlcjEwIiwiaWF0IjoxNjUyMDc1NjU4LCJleHAiOjE2NTIwODI4NTh9.aD4E6N6ZnUlkSTIAmrR3o4jfDYn3hlRt8tg9Cu6LIqg

###

POST http://localhost:3069/auth/email-verification HTTP/1.1
Content-Type: application/json

{
    "id":29,
    "username":"shabrina",
    "email":"Shabrina@mail.com"
}

###

GET http://localhost:3069/auth/verification HTTP/1.1
Content-Type: application/application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NTAsInVzZXJuYW1lIjoidXNlcjE5IiwiaWF0IjoxNjUxMjQxMjkwLCJleHAiOjE2NTEyNDg0OTB9.jIojS_Wx5PqLmdljwBVsjWcfMLndnkqbfxjibtlspVU

###

PATCH  http://localhost:3069/profile/profile-update HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NTQsInVzZXJuYW1lIjoidXNlcjIyIiwiaWF0IjoxNjUxMzY0MzI4LCJleHAiOjE2NTEzNzE1Mjh9.Y9jAoHi4LtV7ReBgfkd7ZgA0C7FD2AhvlEManZdbwMg

{
    "username" : "user22",
    "fullname" : "IM THE REAL USER21",
    "bio" : "THE ONLY USER 21 AROUND YOOO"
}

###

DELETE http://localhost:3069/recipe/delete-recipe HTTP/1.1
Content-Type: application/application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzYsInVzZXJuYW1lIjoidXNlcjEwIiwiaWF0IjoxNjUyMTAzOTY5LCJleHAiOjE2NTIxMTExNjl9.wFZWJB8Ao3d8G9szZk8QojsoOQ5T0YTKiC4TZgEhXEI

{
    "post_id" : "5"
}